### ISSUE TITLE
Using LOOP_INTERVAL in calculate_steering_adjustment()

### ISSUE THREAD

**Issue by Nikitarc** [ukmars/mazerunner-core#8]
profile.h  calculate_steering_adjustment()

I don't understand the line 151:

`float adjustment = (pTerm + dTerm) * LOOP_INTERVAL;`

I would have understood `dTerm * LOOP_FREQUENCY` or `dTerm / LOOP_INTERVAL` as dTerm is dx/dt.

But why `pTerm  * LOOP_INTERVAL`  ?

**Comment by micromouseonline** [comment]
This is actually in sensors.h and is indeed an error.

Thank you for noticing.

I have push a change that should fix it.
